#!/bin/bash

(cat /proc/1/environ; echo) | tr '\000' '\n' |grep GATEWAY > /tmp/jinfo.dat
(cat /proc/1/environ; echo) | tr '\000' '\n' |grep WID >> /tmp/jinfo.dat
(cat /proc/1/environ; echo) | tr '\000' '\n' |grep QDESC >> /tmp/jinfo.dat

source /tmp/jinfo.dat

# start the worker
cd /opt/apps/scivm/scivm-worker
GATEWAY=$GATEWAY WID=$WID QDESC=$QDESC python job_task.py 
